//
//  File generated by HDevelop for HALCON/DOTNET (C#) Version 12.0
//
//  This file is intended to be used with the HDevelopTemplate or
//  HDevelopTemplateWPF projects located under %HALCONEXAMPLES%\c#

using System;
using HalconDotNet;

public partial class HDevelopExport
{
  public HTuple hv_ExpDefaultWinHandle;

  // Main procedure 
  private void action()
  {


    // Local iconic variables 

    HObject ho_Image, ho_GrayImage, ho_Regions;

    // Local control variables 
    // Initialize local and output iconic variables 
    HOperatorSet.GenEmptyObj(out ho_Image);
    HOperatorSet.GenEmptyObj(out ho_GrayImage);
    HOperatorSet.GenEmptyObj(out ho_Regions);
    ho_Image.Dispose();
    HOperatorSet.ReadImage(out ho_Image, @"D:\programresource\ReadImage\ReadImage\Image");
    //dev_open_window(...);
    ho_GrayImage.Dispose();
    HOperatorSet.Rgb1ToGray(ho_Image, out ho_GrayImage);
    ho_Regions.Dispose();
    HOperatorSet.Threshold(ho_GrayImage, out ho_Regions, 10, 95);
    HOperatorSet.DispObj(ho_Regions, hv_ExpDefaultWinHandle);
    ho_Image.Dispose();
    ho_GrayImage.Dispose();
    ho_Regions.Dispose();

  }

  public void InitHalcon()
  {
    // Default settings used in HDevelop 
    HOperatorSet.SetSystem("width", 512);
    HOperatorSet.SetSystem("height", 512);
  }

  public void RunHalcon(HTuple Window)
  {
    hv_ExpDefaultWinHandle = Window;
    action();
  }

}

